### ISSUE TITLE
SASS - Support for @import partials

### ISSUE THREAD

**Issue by rasmusjp** [anaisbetts/SassAndCoffee#1]
When using @import to import partials in SASS I get a Syntax Exception.

It would be great if it could be supported.

**Comment by anaisbetts** [comment]
I suspected that this feature didn't work, it'll take some fiddling in the ResourceAwarePal to get it to know about the current directory, etc. Thanks for the bug report!

**Comment by anaisbetts** [comment]
This is fixed in 0.9 - thanks!
