### ISSUE TITLE
Support CSS passthroughs

### ISSUE THREAD

**Issue by gavacho** [anaisbetts/SassAndCoffee#10]
Consider implementing something similar to SassAndCoffee.Core/Compilers/JavascriptPassthroughCompiler.cs for CSS files.  In an IIS6 environment, I have registered the .css file suffix to the aspnet_isapi.dll executable (disabling the verification that the file exists).  This works wonderfully for .css urls which are handled by the SassFileCompiler.  However, for actual .css files where no corresponding .sass or .scss file exists, an empty response is returned to the client.

**Comment by kogir** [comment]
Fixed in v2.0
