### ISSUE TITLE
Set default build action for .sass, .scss and .coffee files to "content"

### ISSUE THREAD

**Issue by gavacho** [anaisbetts/SassAndCoffee#11]
According to http://blog.andreloker.de, this can be accomplished by placing a file with a pkgdef extension anywhere in VS's Extensions directory with this content:

; Visual Basic
[$RootKey$\Projects{F184B08F-C81C-45f6-A57F-5ABD9991F28F}\FileExtensions.coffee]
"DefaultBuildAction"="Content"

[$RootKey$\Projects{F184B08F-C81C-45f6-A57F-5ABD9991F28F}\FileExtensions.sass]
"DefaultBuildAction"="Content"

[$RootKey$\Projects{F184B08F-C81C-45f6-A57F-5ABD9991F28F}\FileExtensions.scss]
"DefaultBuildAction"="Content"

; C#
[$RootKey$\Projects{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\FileExtensions.coffee]
"DefaultBuildAction"="Content"

[$RootKey$\Projects{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\FileExtensions.sass]
"DefaultBuildAction"="Content"

[$RootKey$\Projects{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}\FileExtensions.scss]
"DefaultBuildAction"="Content"

**Comment by anaisbetts** [comment]
Awesome! I'm going to try to get this into a custom install.ps1 file

**Comment by anaisbetts** [comment]
Fixed as of 3c1a2287c93c
