### ISSUE TITLE
Cache is not invalidated when an @imported stylesheet changes

### ISSUE THREAD

**Issue by gavacho** [anaisbetts/SassAndCoffee#12]
A configuration option to disable caching would be a good workaround

**Comment by anaisbetts** [comment]
Ah, good catch, I'll look into this.

## 

Paul Betts

SENT FROM MY COMMODORE 64: RESPONSES MAY BE IN ALL CAPS

**Comment by anaisbetts** [comment]
I wonder how I can fix this properly without having to reach into Sass's internals...

**Comment by gavacho** [comment]
One option is to set up a FileSystemWatcher to be notified whenever .scss, .sass files are updated and invalidate all cached css.

**Comment by anaisbetts** [comment]
That's the brute-force method, I'd rather have only the dependent
files be invalidated, but that might be too hard.

On Sat, Jul 9, 2011 at 6:40 PM, gavacho
reply@reply.github.com
wrote:

**Comment by kogir** [comment]
You can hook into the PlatformAdaptationLayer and log all files accessed during Sass compilation. It's not the most elegant thing ever, but check out my implementation:

https://github.com/kogir/SassAndCoffee/blob/refactor/SassAndCoffee.Core/Sass/ResourceRedirectionPlatformAdaptationLayer.cs
https://github.com/kogir/SassAndCoffee/blob/refactor/SassAndCoffee.Core/Sass/SassCompiler.cs

The dependentFileList passed into the SassCompiler::Compile method is populated with all files accessed during the Sass compilation.

**Comment by anaisbetts** [comment]
It's the best solution I've heard yet for this problem, let's take it.

On Thu, Dec 1, 2011 at 8:14 PM, Nick Sivo
reply@reply.github.com
wrote:

**Comment by kogir** [comment]
Fixed in v2.0
