### ISSUE TITLE
Problem combining + minifying jQuery with plugins

### ISSUE THREAD

**Issue by fjeldstad** [anaisbetts/SassAndCoffee#15]
I'm using jQuery together with [jQuery.tmpl](http://api.jquery.com/jquery.tmpl/) and would like to minify and combine them into a single .js file referenced by the web app. I've added them to a `base.combine` file that looks like this:

```
jquery-1.6.2.min.js
jQuery.tmpl.min.js
```

However, when the page is loaded I get a Javascript error that says:

> Uncaught TypeError: undefined is not a function

If I instead use pre-minified versions of the files (which I've named *.minorig.js) like this...

```
jquery-1.6.2.minorig.js
jQuery.tmpl.minorig.js
```

...everything works. So that's a workaround, but it would feel a lot cleaner to let SassAndCoffee handle _all_ minifications.

**Comment by hallatore** [comment]
I have the same issue.

Seems to be some sort of problem when combining the auto-minified files. separated they work fine.

**Comment by ShirtlessKirk** [comment]
This happens when a closure is followed by another.

When the files are minified in combination a semi-colon is needed as a separator between each minified file content.
In other words:
```(function(a,b){/\* This could be jQuery _/})(window);
(function(a,b){/_ some plugin */}(this))

``````

To fix:
SassAndCoffee.Core/Compilers/FileConcatenationCompiler.cs line 51
```acc.Append(";\n");
``````

Edit: Pull request added

**Comment by kogir** [comment]
This should have been fixed when xpaulbettsx merged ShirtlessKirk's changeset:
xpaulbettsx/SassAndCoffee@e470c6a5fbcdbfd95e17cb8fd57f9d63913ce340

Please re-open if it's still a problem.
