### ISSUE TITLE
High RAM/CPU use

### ISSUE THREAD

**Issue by tweir** [anaisbetts/SassAndCoffee#23]
I tried deploying an app using SassAndCoffee today. When I fired up the site in IIS, and made an initial request, memory usage spiked to about 700MB, and pegged one of the cores. The process itself was non-responsive. After a bit of trial and error, I disabled SassAndCoffee, and the memory/cpu usage went down to about 100MB, and minimal CPU.

No files were written to App_Data. As a test, I set the perms on App_Data to Everyone:Full Control; it didn't make a difference.

Is there anyway to get some sort of diagnostic information out of SassAndCode to figure out what's going on?

I successfully ran the same app build on a staging server prior to moving it out to the production server. There were zero issues on the staging server, which has a similar, but not identical, configuration as the production server. Both are Win2K8 R2/IIS 7.5.

All code for the app is available here: http://code.geekwerks.ca/clientprefs

**Comment by anaisbetts** [comment]
Can you try upgrading to the latest version and see what happens? 

## 

Paul Betts paul@paulbetts.org

**Comment by kogir** [comment]
I have this same problem with the latest version from NuGet (1.1) as well.  I've taken a process dump and will start to look into it.  Works fine on my dev machine (Win 7 x64), but completely dies on production (2008 R2 x64)

**Comment by anaisbetts** [comment]
Alright, try again with version 1.1.5 which I just pushed
