### ISSUE TITLE
CoffeeScript compilation seems to use bare mode

### ISSUE THREAD

**Issue by ScottWeinstein** [anaisbetts/SassAndCoffee#27]
It would be nice if there were an option to turn this off

**Comment by ahjohannessen** [comment]
Second that. It is something that makes me use another alternative if this is not possible.

**Comment by kogir** [comment]
I'm working on a fix for this.  Would the preferred behavior be to default to normal (non-bare), and signal bare with a .bare.js extension?

file.coffee => raw coffee file
file.js => compiled js file (not bare)
file.bare.js => compiled js (bare)

**Comment by ahjohannessen** [comment]
I think the preferred behavior should be like the behavior on the coffeescript compiler itself. Default to non-bare mode, just as you stated.

**Comment by kogir** [comment]
Fixed in version2 branch.  Thanks for bringing this up!
