### ISSUE TITLE
CSS bundling / combine support

### ISSUE THREAD

**Issue by mboltuc** [anaisbetts/SassAndCoffee#3]
I noticed you have JS bundling which is awesome.  Are there plans to add CSS bundling as well?

**Comment by anaisbetts** [comment]
Definitely, as soon as I find a suitable CSS minifier.

**Comment by mboltuc** [comment]
awesome, the one I've seen floating around most is http://developer.yahoo.com/yui/compressor/ for minification

**Comment by robrbecker** [comment]
SASS will compress css if you give it the :compressed style. Combined with the recently added @import directive being supported, you're all set.

**Comment by anaisbetts** [comment]
Cool! thanks for the tip!

On Mon, Jun 27, 2011 at 4:19 PM, robrbecker
reply@reply.github.com
wrote:

**Comment by kogir** [comment]
I'll look into this in the next few weeks.  Need to kill writing cache files too.
For my later reference: https://github.com/nex3/sass/blob/master/doc-src/SASS_REFERENCE.md

What's the best way to expose the options?  I can use .min.css for :style => :compressed.  Should anything else be configurable?

**Comment by robrbecker** [comment]
Yes I was hoping for .min.css.  Also, not sure if it looks at the file
extension (.sass vs .scss) to determine the :syntax option but that would
be cool.

On Mon, Dec 19, 2011 at 9:11 PM, Nick Sivo <
reply@reply.github.com

> wrote:
> 
> I'll look into this in the next few weeks.  Need to kill writing cache
> files too.
> For my later reference:
> https://github.com/nex3/sass/blob/master/doc-src/SASS_REFERENCE.md
> 
> What's the best way to expose the options?  I can use .min.css for :style
> => :compressed.  Should anything else be configurable?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/xpaulbettsx/SassAndCoffee/issues/3#issuecomment-3214174

## 

-- Rob

**Comment by kogir** [comment]
The current code already supports .sass and .scss extensions correctly.  I'll add .min support and wait for people to ask before tackling the other options.

**Comment by anaisbetts** [comment]
:+1: for .min.css being run through the SCSS compiler

## 

Paul Betts

SENT FROM MY COMMODORE 64: RESPONSES MAY BE IN ALL CAPS

**Comment by kogir** [comment]
And... done.
0d7149f3742378ceaf2a9559517a04a4e83db157
