### ISSUE TITLE
Can't access minified JS

### ISSUE THREAD

**Issue by drewschrauf** [anaisbetts/SassAndCoffee#32]
I've just done a fresh install of SassAndCoffee and created a simple test.coffee file in my scripts folder. When attempting to access this as `/scripts/test.js` everything works fine but when I attempt to load `/scripts/test.min.js` I get the following error:

```
TypeError: Cannot call method 'parse' of undefined
```

This is returned with status 200. Any ideas? Thanks!

**Comment by kogir** [comment]
The latest code in the master branch now supports this.  If a file exists it is served as-is.

**Comment by kogir** [comment]
Fixed in v2.0
