### ISSUE TITLE
Far Future Caching

### ISSUE THREAD

**Issue by mwrock** [anaisbetts/SassAndCoffee#34]
It looks as though SassAndCoffee does not currently support far future caching. From what I can tell based on a brief inspection of the source, it currntly sets a max-age header to no longer than 1 hour. I don't see a codeless way to override that. Just curious if I am missing something, if this is intentional, or if its just something no one has gotten to.

**Comment by kogir** [comment]
I'm not sure of the behavior in the latest NuGet release, but if you're referring to the latest code you're correct.  I'll work on moving the caching settings to a cache profile in web.config which can be easily altered.

**Comment by kogir** [comment]
If you need this immediately, it should be possible with the code in the version2 branch.  Check out the web.config file in the WebTest project and the PipelineHandler in the ASP.Net project to see how it works.

**Comment by kogir** [comment]
Fixed in v2.0

**Comment by mwrock** [comment]
nice. great turnaround!
