### ISSUE TITLE
xunit console runner hangs after running coffee script tests

### ISSUE THREAD

**Issue by mwrock** [anaisbetts/SassAndCoffee#36]
I'm using v1.1.5 of  SassAndCoffee.Core (the latest nuget version) and have Unit Tests around my coffee compilation. They all pass and everything works fine with test driven.net but after all my tests pass using the xunit console runner in my build script, XUnit hangs and the entire build freezes. I've tried calling JS.Shutdown() and new CoffeeScriptCompiler().Dispose() but the runner still hangs.

I've noticed this project uses xunit as well and am curious if you have seen this. BTW: I've testing on both 32 and 64 bit laptop.

Tests are here:
https://github.com/mwrock/RequestReduce/blob/master/RequestReduce.Facts/SassLessCoffee/CoffeeHandlerFacts.cs

Class tested:
https://github.com/mwrock/RequestReduce/blob/master/RequestReduce.SassLessCoffee/SassAndCoffeeHandler.cs

Thanks!

**Comment by kogir** [comment]
Without running your tests - I noticed the same behavior just running the SassAndCoffee internal tests.  I think it was related to the thread hosting V8 not being marked as a background thread and never being shutdown correctly.  As long as it's still running the AppDomain won't unload.

In v2 the code uses the JScript engine that ships with Windows and IE.  All the apartment/threading is managed by COM and handled correctly.  Switching to v2 is a potentially breaking change (hence the version bump), so if that's not possible look into changing the threading code in v1.1.5

**Comment by mwrock** [comment]
Thanks Nick. 

Oh boy. Apartment threading. That hearkens back memories that I'd rather not dwell on with sharp objects close by.

I don't have too much code to break. I've looked at some of the v2 stuff and it does look cleaner so I plan to migrate as soon as its available via Nuget. My project RequestReduce.SassLessCoffee takes SassAndCoffee on as a dependency and its just a much better install story for consumers. Do you know what the timeline is to get SassAndCoffee v2 on Nuget?

Thanks,
Matt

**Comment by kogir** [comment]
I'm not an owner of the NuGet package, but I'll shoot an email to @xpaulbettsx and see what he thinks.

**Comment by mwrock** [comment]
Took care of this for now by using a static method counter (I have 4) in the test class' Dispose:

```
    public void Dispose()
    {
        if(++count == 4) //don't let the kids see this
            JS.Shutdown();
    }
```

Certainly not the most elegant solution but its quick and easy and I plan to yank it out as soon as you release 2.0 on Nuget. Thanks.
