### ISSUE TITLE
CoffeeScript files can't have the same name

### ISSUE THREAD

**Issue by taylorsmith** [anaisbetts/SassAndCoffee#37]
When using a `.combine` manifest, an issue occurs when 2 or more files have the same name, e.g.

```
app/feature/main.js
app/main.js
```

Perhaps an md5 should be used for the `App_Data` files instead of a timestamp?

**Comment by kogir** [comment]
The new caching code in v2.0 no longer has this problem.

**Comment by taylorsmith** [comment]
Is 2.0 out yet? I'm still seeing 1.1.5 on NuGet.
