### ISSUE TITLE
.combine not working for jQuery.validate.min.js

### ISSUE THREAD

**Issue by jakejscott** [anaisbetts/SassAndCoffee#5]
Hi Paul I have just downloaded and ran the SassAndCoffee.WebTest website. 

I changed it to use the minified javascript and get errors on page load in firebug

<script src="@Url.Content("~/Scripts/prod_all.js")" type="text/javascript"></script>

I think there is a problem with the way jQuery.validate.min.js and jquery.validate.unobtrusive.min.js have been minified?

Cheers
Jake

**Comment by anaisbetts** [comment]
Hmmm, I'll take a look - might be a bug in Uglify. Thanks!

**Comment by RoyTinker** [comment]
I know uglifyjs has some potentially unsafe transformations that it takes - the author documents this. Perhaps a flag/setting could be passed that would avoid all potentially unsafe transformations? (By the way, I'm getting errors when minifying json.js from json.org).

**Comment by kogir** [comment]
This should be fixed now both by a) using the file on disk if it already exists (don't minify a minified file), and b) the fix to xpaulbettsx/SassAndCoffee#15
