### ISSUE TITLE
ASP.NET runtime error: A section using 'configSorsce' may contain no other attributes or elements.

### ISSUE THREAD

**Issue by ilyador** [anaisbetts/SassAndCoffee#53]
This error appears under a lot of lines in the MVC3 Razor view files, referencing to Web.config file to this line:
< remove key="SassAndCoffee.Cache" / >
and the project can't be built

**Comment by kogir** [comment]
Oops.  I bungled the configuration transform in the nuget package.  Find that line in your web.config and remove it.
