### ISSUE TITLE
Longer precompiled JS files not reliably returned

### ISSUE THREAD

**Issue by ScottWeinstein** [anaisbetts/SassAndCoffee#7]
To repeat the problem in chrome, get an existing JS file, say unminified jQuery multiple times.

In Chrome, about on alternating requests I get the following:

```
This webpage is not available
The webpage at https://localhost:44300/Scripts/jquery-1.5.2.js might be temporarily down or it may have moved   permanently to a new web address.
Error 330 (net::ERR_CONTENT_DECODING_FAILED): Unknown error.
```

In FF 3.6 I get

```
Content Encoding Error
The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.
```

and IE 10 is 

```
 Internet Explorer cannot display the webpage 
```

I've tried to find the source of the error, so far no luck.

**Comment by anaisbetts** [comment]
I'll look into this, thanks for the bug report

## 

Paul Betts paul@paulbetts.org

**Comment by anaisbetts** [comment]
Oops, this slipped off my radar, will try to take a look at it soon

**Comment by ScottWeinstein** [comment]
Would be great. FYI - I've only tested w/ IIS express. Not sure about IIS or cassini.

**Comment by anaisbetts** [comment]
It looks like if you have a _really_ long file (I was trying with 10MB worth of jQuery UI), you can blow the stack (i.e. StackOverflowException).  I'll try to give you more headroom by increasing the thread stack size, but in the meantime, I recommend splitting things into smaller files. Why are you making users download all that crap anyways?? ;)

**Comment by ScottWeinstein** [comment]
I'm afraid I didn't describe the problem accurately. Sorry about that. 

The problem isn't only limited to huge files but occurs intermittently on small files (5K), and more frequently when downloading larger (200k) JS files. 

I discovered the problem when I tried to use SassAndCoffee and it worked on every other browser request. I had existing compiled coffee files, and when SassAndCoffee tried to server up the existing .js file it failed on alternating requests.

When I tried to duplicate the problem in a virgin project, it was only on the larger js files that the problem would show.

**Comment by jakcharlton** [comment]
I get exactly this problem - hitting the Refresh button on the page reliably causes it on every other request.

First is fine, all JS returned, next returns no JS, and so on alternating between JS/No JS 

And these are just .js files - no coffee ones at all

**Comment by anaisbetts** [comment]
Interesting, I don't repro this at _all_. Can you tell me more about your environment and browser?

**Comment by jakcharlton** [comment]
Nothing much unusual, Chrome was browser, HTML was out of ASP.NET MVC, with HTML5 Boilerplate template mostly intact.

Seemed to be some kind of caching going on, random initial requests caused it to fail, repeat Refresh clicks alternated, clicking in page links didn't.

Had to remove SassAndCoffee as JS was more important to me than trying to get Sass working :)

**Comment by anaisbetts** [comment]
OS? Architecture? VS version? VS SP level?

## 

Paul Betts

SENT FROM MY COMMODORE 64: RESPONSES MAY BE IN ALL CAPS

**Comment by jakcharlton** [comment]
Win7, MVC, VS2010 SP1

**Comment by ScottWeinstein** [comment]
Win7 x64, MVC, VS2010 SP1, IIS Express

**Comment by gavacho** [comment]
Also encountering this on win server 2008 64, fx4 framework, running in 32 app pool.  It's like every other request to a .js file chokes with Error 330 (net::ERR_CONTENT_DECODING_FAILED): Unknown error.

**Comment by jakcharlton** [comment]
Yrah forgot to mention mine was Win7 x64 if that makes a difference

**Comment by gavacho** [comment]
My issue seems to have been resolved by installing windows updates after installing fx4 on the server.

EDIT: Nevermind, issue persists.  The issue only presents itself when requesting the .js from a remote computer (not localhost)

**Comment by jimmy2saints** [comment]
I'll add to this same issue. Win7 64, MVC project, vs2010 sp1, iis express.
Every second requests gives  (net::ERR_CONTENT_DECODING_FAILED).
(The requested JS file in this case is modernizr-2.0.6-development-only.js)

**Comment by anaisbetts** [comment]
I believe I've fixed this - can someone who hit this before try again and reopen if it's still borked?

**Comment by grumpydev** [comment]
@xpaulbettsx is this something I need to look at it Nancy.SassAndCoffee, or is it an ASP.Net peculiarity ?

**Comment by anaisbetts** [comment]
The fix is in AspNet, you're probably good

## 

Paul Betts paul@paulbetts.org

**Comment by ScottWeinstein** [comment]
looks good
